#!/bin/bash
source /u/cs241/setup

java cs241.binasm < ${1}.asm > ${1}.mips
java mips.array ${1}.mips < ${2}.in > ${3} 2> ${2}.err
grep -oP "03 = 0x0{0,8}([0-9a-fA-F]{0,8})" ${2}.err > ${3}
rm ${1}.mips
